[package]
name = "rfctk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "rfctk"
path = "src/lib.rs"

[[bin]]
name = "rfc"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.75"
ansi_term = "0.12.1"
